Add Image Ranking Reward Dataset
withmartian/multinomial_reward pull request #5
Opened 2023-08-24 17:44 UTC by jacobbieker

This PR is a subset of #3 that is only comprised of the ImageRankingDataset and related changes.

The ImageRankingDataset can take the screenshots folder from #4 and make a ranked reward training dataset out of it. 

This can then be used with the vision model support in to train ViT-based image models in ranked rewards.

Current (but soon to be lifted) limitation is that the files have to be local. Will be adding support for GCP and remote files soon.

2023-08-25 00:53 UTC, amydeng2000 requested changes
it was super helpful to read through your code! Left some comments and questions.

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +        images = [sublist for sublist in images if sublist]  # remove empty sublists of slices
just making sure I got this correctly.. I thought `resize_and_slice` will never return an empty list because you always append to it before you return?

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +        key=lambda x: int(x.split("/")[-1].split("_")[1]),
does this sort by year in ascending order? if so can we make a comment :)

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            websites = sorted(list(set([file.split("/")[-1].split("_")[0] for file in files])))
what is this sorting by? plz make a comment, same as the sorted() in line 182

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            labels = [i for i in range(min(current_counts[0], self.max_ranks_per_batch))]
so we are giving small labels to earlier (worse) websites. Does that mean the eval dataset should also come in ordered lists of worst -> best?

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            labels = [i for i in range(min(current_counts[0], self.max_ranks_per_batch))]
also, I *think* because you made sure you don't have at most `max_ranks_per_batch` images in line 222, we don't need all the `min(__, self.max_ranks_per_batch)` that's in DataCollator, unless DataCollator have a different `max_ranks_per_batch` than the ImageDataset, but I don't think that'd make sense

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            labels.extend([self.max_ranks_per_batch + 1] * (self.max_ranks_per_batch - len(labels)))
can you help me understand why we are adding max_ranks_per_batch +1 for ranks where images don't exist, instead of -1 or some other value?

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            current_counts[0] = min(current_counts[0], self.max_ranks_per_batch)
let's rename `current_counts[0]` to something more readable since we refer to this value a few more times later

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            current_counts[0] = min(current_counts[0], self.max_ranks_per_batch)
same with current_counts[1]

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +                for j in range(current_counts[1][i]):  # Number of images per year
I am a little confused here... so we are not pooling the tensors for the image slices but rather just appending them in one list `pixel_values`. So wouldn't pixel_values have a max length of  `max_ranks_per_batch` * `slice_count` (since the max value for `current_counts[0]` is `max_ranks_per_batch`)?  Then why is the comment on line 269 says all the pixel_values should have a length of `max_ranks_per_batch` after padding? I feel like I missed something here

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +                counts[1].append(current_counts[1][i] if i < len(current_counts[1]) else 1)
making sure I got this right
`counts[0]` is the number of years with valid images (non zero images)
`counts[1]` is a list containing number of slices we have for each year

2023-08-25 00:53 UTC, amydeng2000 commented on src/dataset.py
> +            if idx == 0:
why is `collated_batch["pixel_values"]` or `collated_batch["labels"]` not updated when idx==0

2023-08-25 06:56 UTC, jacobbieker commented on src/dataset.py
> +        max_ranks_per_batch: int = 27,
It was originally from that yes, although all the scraping I've done stops at 2001, so probably can update the default.

2023-08-25 08:10 UTC, jacobbieker commented on src/dataset.py
> +
Yes, but the height and width might not be the same. In the models, I've added some support for training on sizes the original models were not trained on, such as 896x672, so both are not necessarily true. The idea behind returning the smaller images without scaling them is that it keeps the original placement and relationships between the parts of the screenshot in the correct place, and limits distortions from resizing it.

2023-08-25 08:14 UTC, jacobbieker commented on src/dataset.py
> +                if i + desired_width <= img.width and j + desired_height <= img.height:
This code takes multiple slices per input screenshot if its too big, so should capture the whole screenshot, including the footers. There is the option to limit the number of image slices to return, which then could lead to removing the footers more often than not. The model updates in #6 also average the outputs from all the images per screenshot, so the models should still see the entirety of the website screenshot. But yeah, do agree slicing isnt necessarily the best option

2023-08-25 08:14 UTC, jacobbieker commented on src/dataset.py
> +        key=lambda x: int(x.split("/")[-1].split("_")[1]),
Yes, and yes, will add that

2023-08-25 16:15 UTC, jacobbieker commented on src/dataset.py
> +        images = [sublist for sublist in images if sublist]  # remove empty sublists of slices
Yes, you are right, I'll remove this bit.

2023-08-25 16:25 UTC, jacobbieker commented on src/dataset.py
> +            labels.extend([self.max_ranks_per_batch + 1] * (self.max_ranks_per_batch - len(labels)))
It was arbitrary, having a number outside the range that is expected, but yeah -1 makes more sense, so changed it to that.

2023-08-25 16:28 UTC, jacobbieker commented on src/dataset.py
> +                counts[1].append(current_counts[1][i] if i < len(current_counts[1]) else 1)
Yes, I've renamed them to hopefully be clearer

2023-08-25 16:38 UTC, jacobbieker commented on src/dataset.py
> +                for j in range(current_counts[1][i]):  # Number of images per year
Yeah, I removed the nested loop, its redundant actually. The pixel values do have a max length of `max_ranks_per_batch` * `slice_count`. We do add empty images for missing years, essentially on line 269, so that there is at least 1 image tensor per rank, even if its just padding. The model in #6  will ignore it and discard the empty image tensors similar to the padding in the text inputs.

2023-08-25 16:44 UTC, jacobbieker commented on src/dataset.py
> +            if idx == 0:
Because for idx==0,  `collated_batch["pixel_values"]` is already just a single PyTorch tensor, and same with `collated_batch["labels"]`, so there is no need to use `torch.cat` or anything. They both already have the shape `[Batch, Channel, Width, Height]` and so is in the correct shape already.  `collated_batch["counts"]` is changed to just to add the list that will be appended to, otherwise the structure of `collated_batch["counts"]` becomes incorrect.

2023-08-25 17:55 UTC, amydeng2000 commented on src/dataset.py
> +            websites = sorted(list(set([file.split("/")[-1].split("_")[0] for file in files])))
sorry what do you mean by order stays consistent across runs? you mean for training runs / when the dataset is prepped each time? Does this help to debug the model?

2023-08-25 17:56 UTC, amydeng2000 commented on src/dataset.py
> +            if idx == 0:
ah yes you're right, thanks for explaining!

2023-08-25 18:10 UTC, amydeng2000 commented on src/dataset.py
> +                for j in range(current_counts[1][i]):  # Number of images per year
Making sure I got this right -- current pixel values is a flat list of all the slices' `pixel_values` after `self.process`. It goes in the sequence of 
```
img1_slice1, img1_slice2, Image2_slice1, .... padded_zero_images, padded_zero_images
```
so if for this website, we only have 2 years, and they each have 2 slices, we would have `len(current_pixel_values) == 2*2 + (max_ranks_per_batch - 2)` Is that right?

2023-08-25 18:11 UTC, amydeng2000 commented on src/dataset.py
> +                for j in range(current_counts[1][i]):  # Number of images per year
I haven't looked closely at the model code, but I assume some sort of averaging is happening there for the slices of each website?

2023-08-25 18:22 UTC, jacobbieker commented on src/dataset.py
> +            websites = sorted(list(set([file.split("/")[-1].split("_")[0] for file in files])))
Yes, since `set` doesn't guarantee any specific ordering, doing this can help with debugging training, or if we set random seeds to make reproducible runs, this should help ensure that works. It shouldn't really matter the order, so I figured might as well have the websites sorted. PyTorch will take random indices anyway when training.

2023-08-25 18:29 UTC, jacobbieker commented on src/dataset.py
> +                for j in range(current_counts[1][i]):  # Number of images per year
Yes, the `pixel_values` is ```img1_slice1, img1_slice2, Image2_slice1, .... padded_zero_images, padded_zero_images``` And yes, for a websites with 2 years of screenshots, each of two slices, that would be the correct amount of images for `len(current_pixel_values)`

And yes, in the model code, it get the output embedding for each image, so the raw output from the model would be 

``` img1_slice1_embedding, img1_slice2_embedding, Image2_slice1_embedding, ..., padded_zero_image_embedding, padded_zero_image_embedding``` 

The model then, for `img1` does ```avg(img1_slice1_embedding, img1_slice2_embedding) = img1_embedding``` so that what is used for the ranked reward calculations is then ```img1_embedding, img2_embedding``` as the ```padded_zero_image_embedding``` is ignored.

2023-08-25 21:34 UTC, amydeng2000 approved these changes

2023-08-26 07:33 UTC, jacobbieker commented on src/dataset.py
> +        for rank in range(self.max_ranks_per_batch):
@amydeng2000 I found a bug in #6 in regards to how the order of the images was being used, this code is just moving that extra processing out of ```Model``` and into the collator, but you might want to have a quick look over it?

2023-08-28 18:53 UTC, amydeng2000 commented on src/dataset.py
> +        for rank in range(self.max_ranks_per_batch):
It's hard to make sure everything is correct without being able to run this interactively (if there's a way for you to share a subset of your screenshot folder so I can run this locally that would be great!) But a few clarifying questions

- We pad the ranks but we don't pad each rank to have max_num_slices. Instead, we keep track of how many slices there are for each rank with `batch_data["counts"]` in ImageDataCollator
- I thought `collated_batch["pixel_values"]` at this point is a tensor for all the slices and all padding images in sequence, like you described: [year_2023_slice1, year_2023_slice_2, year_2022_slice_1, ...] But it seems like it not, which is why you added the code below to put it into that form. So what is the `collated_batch["pixel_values"]` at this point?

2023-08-28 19:58 UTC, jacobbieker commented on src/dataset.py
> +        for rank in range(self.max_ranks_per_batch):
The screenshot folder in gcp is a direct copy of my local one, so just downloading a few examples from there should work here! As for the other questions:
1. Yes, we pad ranks, but not to max_num_slices, to try to conserve memory, and use the ```counts``` to keep track of all that
2. ```collated_batch["picel_values"]``` is a tensor for all slices and all padding images in a sequence, first for one website, and then for another, as this is after all the tensors and such are collated. But ```Model``` expects it in a different ordering, so this converts it from [website1_year_2023_slice1, website1_year_2023_slice_2, website1_year_2022_slice_1, ..., website2_year_2023_slice1,...] to [website1_year_2023_slice1, website1_year_2023_slice_2, website2_year_2023_slice_1, ..., website1_year_2022_slice_1, ...]

2023-09-01 00:46 UTC, UYasher requested changes
Generally looks good, mainly had two questions/improvements regarding the structure:

- Separating data loading from creating the ranking dataset
- Reducing code duplication

2023-09-01 00:46 UTC, UYasher commented on src/dataset.py
> +                if i + desired_width <= img.width and j + desired_height <= img.height:
Is there a good alternative to slicing? Could we, for example, have the model generate more tokens for longer images? (Not saying we should necessarily do this -- might be too much engineering time, and the results already seem pretty good, but want to think through the options here)

2023-09-01 00:46 UTC, UYasher commented on src/dataset.py
> +                        image_slices.append(new_img)
Seems like there's significant code duplication here -- why not just rotate and then apply the same function as in the other case?

Same may also be true of the `if tile_horizontal and tile_vertical:` case above.

2023-09-01 00:46 UTC, UYasher commented on src/dataset.py
> +        # Now at least the size of the desired size in both dimensions
I think this comment is trying to say
"Now, both dimensions are at least as large as the desired width and height"

Is that correct?

Furthermore, does it make sense to abstract this into a function rather than commenting about the result?

2023-09-01 00:46 UTC, UYasher commented on src/dataset.py
> +        ),
Thinking a little bit into the future, we'd like to reuse this reward model for non-website images. E.g. what if we have a client who cares about pictures of slide decks, or we want to make a more general purpose multi-modal reward model?

I think it would be preferable to separate data loading from creating the ranking dataset, so we can support more use cases.

One potential implementation would be to take in a list of globs, and to grab the images in a separate utility function/class. Open to other options too.

2023-09-01 00:46 UTC, UYasher commented on src/dataset.py
> +        for rank in range(self.max_ranks_per_batch):
After a first pass on my end, it looks like this works. @amydeng2000, did you get a chance to test this?

2023-09-01 08:51 UTC, jacobbieker commented on src/dataset.py
> +                if i + desired_width <= img.width and j + desired_height <= img.height:
So the models can already do that, and the best performing model did do that too. For example, if the input images are 224x224 dinov2-small outputs 257 tokens, while for the 672x448 input images the best model was trained on, it outputted ~1537 per image. So we could not slice and just take longer images, the downside to that would be a lot more computation if we are padding other, shorter images to the same size. With this, if you know the largest image size that you have, you can set the width/height to that, and no images would be sliced, with smaller ones padded. With this slicing, though, I think it gives some more flexibility compared to padding all the images to the largest sized one, with larger images having multiple slices, but smaller ones just being a single, smaller image.

2023-09-01 08:54 UTC, jacobbieker commented on src/dataset.py
> +                        image_slices.append(new_img)
Yeah, that would work too, I can change it to that

2023-09-01 08:57 UTC, jacobbieker commented on src/dataset.py
> +        ),
Okay, yeah, that makes sense. I think taking the list of globs and a ranking function based off the file names would work pretty well. I'll update it to use that instead.

2023-09-01 21:45 UTC, jacobbieker commented on src/dataset.py
> +        # Now at least the size of the desired size in both dimensions
Yeah, that is correct. I've refactored it now.

2023-09-06 14:45 UTC, jacobbieker commented on src/dataset.py
> +        for rank in range(self.max_ranks_per_batch):
There are now tests that should ensure that this is working as we expect.

2023-09-06 18:11 UTC, UYasher commented on src/dataset.py
> -    )
Where is this logic handled now?

2023-09-06 18:23 UTC, UYasher approved these changes

2023-09-06 18:25 UTC, jacobbieker commented on src/dataset.py
> -    )
This is now will be handled in the file_globs, one of the tests shows how it's done essentially.

2023-09-06 18:30 UTC, merged